name: PlayerHider
main: io.github.redinzane.playerhider.PlayerHider
version: 0.5
description: A simple plugin that tries to hide underground bases by letting players appear sneaked to players that are further away. Also features LoS based hiding

depend: [ProtocolLib]

permissions:
  playerhider.*:
    description: Gives access to everything.
    children:
      playerhider.hide.autosneak: true
  playerhider.hide.autosneak:
    description: Whether or not to hide all automatic sneaking for this player.
    default: op